DIALOGS = {
    'create_ad_info': 'Dichiaro utilizzando questo bot di non vendere e non cercare oggetti fake e di rispettare tutti gli utenti che fanno parte della community',
    'need_reset': 'Utente non riconosciuto, o in stato non consistente, premi /reset per tornare al menu. Oppure, /start per iniziare ad usare il bot',
    'need_start': 'Per iniziare ad usare il bot, digita /start',
    'digit_error': 'Perfavore, inserisci un numero',
    'shoe_size_error': 'Inserire una taglia tra quelle proposte',
    'photo_not_requested': 'Non dovresti mandarmi una foto in questo momento...',
    'ad_success': 'Annuncio inserito! Se ritenuto idoneo dovresti vederlo tra pochi minuti sul canale',
    'type_not_valid': 'Perfavore, selezionare un tipo di annuncio valido',
    'no_ads_error': 'Oops, non hai annunci da rimuovere, premi /reset per tornare al menu',
    'command_not_valid' : 'Comando non permesso in questo momento',
    'brand_not_valid': 'Il brand inserito non è valido, devi selezionare una delle opzioni proposte!',
    'not_valid_choice': 'Perfavore, seleziona una delle opzioni proposte',
    'vote_registered': 'Grazie, il tuo feedback è stato registrato',
    'autovote_error': 'Non puoi auto-valutarti!',
    'user_not_found': 'Utente non trovato',
    'username_not_found': '<b>ATTENZIONE</b> Non hai un username impostato, potrebbe non essere possibile per i tuoi clienti contattarti! Inseriscine uno dalle impostazioni di Telegram!',
    'already_admin': 'Sei già amministratore!',
    'invalid_password': 'Password non corretta!',
    'invalid_set_admin_usage': 'Uso del comando: /setadmin password',
    'admin_set_confirm': 'Sei stato correttamente aggiunto alla lista degli admin',
    'confirm_group_set': 'Gruppo selezionato con successo!',
    'password_updated': 'Password aggiornata con successo!',
    'error_set_password': 'Uso del comando /newpassword vecchiapassword nuovapassword',
    'permission_denied': 'Devi essere un admin per accedere a questo comando!',
    'error_block_ad': 'Uso del comando: /block idannuncio',
    'block_confirm': 'Annuncio bloccato con successo',
    'id_not_found': 'Id annuncio non trovato, riprovare',
    'timer_error': 'Uso del comando: /settimer minuti',
    'timer_success': 'Timer impostato correttamente',
    'no_group_found': 'Non hai selezionato un gruppo privato!',
    'invalid_channel': 'Nome del canale non valido! (Suggerimento, il nome di un canale inizia sempre per \'@\' e non contiene spazi)',
    'channel_change_confirm': 'Canale correttamente modificato!'
}

KEYBOARD_TEXTS = {
    'menu_dialog': 'Cosa vuoi fare? Digita in ogni momento /reset per tornare al menu principale',
    'ad_insert_confirm': 'Confermi di aver letto l\'informativa?',
    'region_select': 'In che regione abiti?',
    'shoe_name_selection': 'Scrivi il nome del modello della scarpa',
    'number_selection': 'Inserisci la taglia della scarpa (US)',
    'condition_selection': 'Seleziona la condizione',
    'price_selection_sell': 'Inserisci il prezzo',
    'price_selection_buy': 'Quanto è il tuo budget?',
    'photo_insertion': 'Manda la foto della tua scarpa',
    'ad_complete_confirm': 'Annuncio creato, vuoi postarlo?',
    'ad_type_select': 'Di che tipo di annuncio si tratta?',
    'delete_ad': 'Seleziona l\'annuncio da rimuovere',
    'brand_selection': 'Seleziona il brand',
    'note_insert': 'Scrivi le tue note',
    'note_insert_req': 'Desideri aggiungere delle note?',
    'set_availability': 'La sneaker è già disponibile?',
    'store_insertion': 'Da quale negozio l\'hai acquistata?',
    'set_shipping': 'Spedisci?',
    'accept_paypal': 'Accetti Paypal Beni e Servizi?',
    'insert_feedback': 'Inserisci l\'username, comprensivo di @, dell\'utente che vuoi valutare',
    'evaluate_feedback': 'Come valuti l\'esperienza con questo utente?',
    'custom_brand_insertion': 'Inserisci il nome del brand'
}
